Block:
  InstanceId: 12345678-9012-3456-7890-123456789012
deployments:
  nginx:
    configuration:
      chart:
        baseRegistryUrl: charts.bitnami.com
        name: NGINX-OVERRIDE
        repo: bitnami
        version: 99.99.99
    values:
      service:
        httpsPort: 999
        port: 999
        type: NodePort
    variables:
      appname: nginx
placement:
  site:
    label: f0f802ff-1888-46d5-931b-16897c3f1de7
