# coding: utf-8

"""
    NBI Service Orchestration API

    Provides a robust interface for orchestrating service chains across cloud and edge computing environments, facilitating deployment, management, and updates of service chains to ensure dynamic, efficient operations across diverse infrastructure setups.

    The version of the OpenAPI document: 1.0.0
    Contact: support@nearbycomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest
from inno_nbi_api.models.chart_key import ChartKey

class TestChartKey(unittest.TestCase):
    """ChartKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChartKey:
        """Test ChartKey
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return ChartKey(
                name='test_name',
                version='1.0'
            )
        else:
            return ChartKey(
                name='test_name'
            )

    def testChartKey(self):
        """Test ChartKey"""
        inst_req_only = self.make_instance(include_optional=False)
        self.assertEqual(inst_req_only.name, 'test_name')
        self.assertIsNone(inst_req_only.version)

        inst_req_and_optional = self.make_instance(include_optional=True)
        self.assertEqual(inst_req_and_optional.name, 'test_name')
        self.assertEqual(inst_req_and_optional.version, '1.0')

if __name__ == '__main__':
    unittest.main()
