# coding: utf-8

"""
    NBI Service Orchestration API

    Provides a robust interface for orchestrating service chains across cloud and edge computing environments, facilitating deployment, management, and updates of service chains to ensure dynamic, efficient operations across diverse infrastructure setups.

    The version of the OpenAPI document: 1.0.0
    Contact: support@nearbycomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest
from inno_nbi_api.models.device_progress import DeviceProgress

class TestDeviceProgress(unittest.TestCase):
    """DeviceProgress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceProgress:
        """Test DeviceProgress
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return DeviceProgress(
                step=56,
                goal=56
            )
        else:
            return DeviceProgress()

    def testDeviceProgress(self):
        """Test DeviceProgress"""
        inst_req_only = self.make_instance(include_optional=False)
        self.assertIsNone(inst_req_only.step)
        self.assertIsNone(inst_req_only.goal)

        inst_req_and_optional = self.make_instance(include_optional=True)
        self.assertEqual(inst_req_and_optional.step, 56)
        self.assertEqual(inst_req_and_optional.goal, 56)

if __name__ == '__main__':
    unittest.main()
