# coding: utf-8

"""
    NBI Service Orchestration API

    Provides a robust interface for orchestrating service chains across cloud and edge computing environments, facilitating deployment, management, and updates of service chains to ensure dynamic, efficient operations across diverse infrastructure setups.

    The version of the OpenAPI document: 1.0.0
    Contact: support@nearbycomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.services_api import ServicesApi


class TestServicesApi(unittest.TestCase):
    """ServicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_service_chain_by_id(self) -> None:
        """Test case for delete_service_chain_by_id

        Delete a deployed service chain by ID
        """
        pass

    def test_deploy_service(self) -> None:
        """Test case for deploy_service

        Deploy a new service chain
        """
        pass

    def test_get_all_deployed_services(self) -> None:
        """Test case for get_all_deployed_services

        Retrieve all deployed service chains
        """
        pass

    def test_get_deployed_service(self) -> None:
        """Test case for get_deployed_service

        Retrieve deployed service chain by ID
        """
        pass

    def test_update_service(self) -> None:
        """Test case for update_service

        Update a deployed service chain
        """
        pass


if __name__ == '__main__':
    unittest.main()
