# coding: utf-8

"""
    NBI Service Orchestration API

    Provides a robust interface for orchestrating service chains across cloud and edge computing environments, facilitating deployment, management, and updates of service chains to ensure dynamic, efficient operations across diverse infrastructure setups.

    The version of the OpenAPI document: 1.0.0
    Contact: support@nearbycomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inno_nbi_api.models.deploy_service_chain_args import DeployServiceChainArgs

class TestDeployServiceChainArgs(unittest.TestCase):
    """DeployServiceChainArgs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeployServiceChainArgs:
        """Test DeployServiceChainArgs
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeployServiceChainArgs`
        """
        model = DeployServiceChainArgs()
        if include_optional:
            return DeployServiceChainArgs(
                name = '',
                blocks = [
                    inno_nbi_api.models.block_args_deploy.BlockArgsDeploy(
                        display_name = '', 
                        block_chart_name = '', 
                        block_chart_version = '', 
                        site_id = '', )
                    ]
            )
        else:
            return DeployServiceChainArgs(
        )
        """

    def testDeployServiceChainArgs(self):
        """Test DeployServiceChainArgs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
