# coding: utf-8

"""
    NBI Service Orchestration API

    Provides a robust interface for orchestrating service chains across cloud and edge computing environments, facilitating deployment, management, and updates of service chains to ensure dynamic, efficient operations across diverse infrastructure setups.

    The version of the OpenAPI document: 1.0.0
    Contact: support@nearbycomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest
from datetime import datetime
from inno_nbi_api.models.block import Block

class TestBlock(unittest.TestCase):
    """Block unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Block:
        """Test Block
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return Block(
                id='1',
                display_name='Test Block',
                owner='owner_id',
                org='org_id',
                blockchart_name='test_chart',
                blockchart_version='1.0',
                blockchart_values='values',
                status='OKTOSTATUS_IN_SYNC',
                created_at=datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                device_ids=['device1', 'device2']
            )
        else:
            return Block(
                id='1'
            )

    def testBlock(self):
        """Test Block"""
        inst_req_only = self.make_instance(include_optional=False)
        self.assertEqual(inst_req_only.id, '1')
        self.assertIsNone(inst_req_only.display_name)
        self.assertIsNone(inst_req_only.owner)
        self.assertIsNone(inst_req_only.org)
        self.assertIsNone(inst_req_only.blockchart_name)
        self.assertIsNone(inst_req_only.blockchart_version)
        self.assertIsNone(inst_req_only.blockchart_values)
        self.assertIsNone(inst_req_only.status)
        self.assertIsNone(inst_req_only.created_at)
        self.assertIsNone(inst_req_only.device_ids)

        inst_req_and_optional = self.make_instance(include_optional=True)
        self.assertEqual(inst_req_and_optional.id, '1')
        self.assertEqual(inst_req_and_optional.display_name, 'Test Block')
        self.assertEqual(inst_req_and_optional.owner, 'owner_id')
        self.assertEqual(inst_req_and_optional.org, 'org_id')
        self.assertEqual(inst_req_and_optional.blockchart_name, 'test_chart')
        self.assertEqual(inst_req_and_optional.blockchart_version, '1.0')
        self.assertEqual(inst_req_and_optional.blockchart_values, 'values')
        self.assertEqual(inst_req_and_optional.status, 'OKTOSTATUS_IN_SYNC')
        self.assertEqual(inst_req_and_optional.created_at, datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'))
        self.assertEqual(inst_req_and_optional.device_ids, ['device1', 'device2'])

if __name__ == '__main__':
    unittest.main()
