# coding: utf-8

"""
    NBI Service Orchestration API

    Provides a robust interface for orchestrating service chains across cloud and edge computing environments, facilitating deployment, management, and updates of service chains to ensure dynamic, efficient operations across diverse infrastructure setups.

    The version of the OpenAPI document: 1.0.0
    Contact: support@nearbycomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest
from inno_nbi_api.models.okto_resource import OktoResource

class TestOktoResource(unittest.TestCase):
    """OktoResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OktoResource:
        """Test OktoResource
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return OktoResource(
                id='test_id',
                name='test_name',
                kind='test_kind',
                status='OKTOSTATUS_IN_SYNC',
                namespace='test_namespace',
                manifest='test_manifest'
            )
        else:
            return OktoResource(
                id='test_id',
                name='test_name'
            )

    def testOktoResource_required_only(self):
        """Test OktoResource with only required params"""
        inst_req_only = self.make_instance(include_optional=False)
        self.assertEqual(inst_req_only.id, 'test_id')
        self.assertEqual(inst_req_only.name, 'test_name')
        self.assertIsNone(inst_req_only.kind)
        self.assertIsNone(inst_req_only.status)
        self.assertIsNone(inst_req_only.namespace)
        self.assertIsNone(inst_req_only.manifest)

    def testOktoResource_required_and_optional(self):
        """Test OktoResource with required and optional params"""
        inst_req_and_optional = self.make_instance(include_optional=True)
        self.assertEqual(inst_req_and_optional.id, 'test_id')
        self.assertEqual(inst_req_and_optional.name, 'test_name')
        self.assertEqual(inst_req_and_optional.kind, 'test_kind')
        self.assertEqual(inst_req_and_optional.status, 'OKTOSTATUS_IN_SYNC')
        self.assertEqual(inst_req_and_optional.namespace, 'test_namespace')
        self.assertEqual(inst_req_and_optional.manifest, 'test_manifest')

if __name__ == '__main__':
    unittest.main()
