# coding: utf-8

"""
    NBI Service Orchestration API

    Provides a robust interface for orchestrating service chains across cloud and edge computing environments, facilitating deployment, management, and updates of service chains to ensure dynamic, efficient operations across diverse infrastructure setups.

    The version of the OpenAPI document: 1.0.0
    Contact: support@nearbycomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest
from inno_nbi_api.models.device_cloud_resource_chart import DeviceCloudResourceChart
from inno_nbi_api.models.chart_key import ChartKey
from inno_nbi_api.models.device_cloud_resource_chart_latest_config_inner import DeviceCloudResourceChartLatestConfigInner

class TestDeviceCloudResourceChart(unittest.TestCase):
    """DeviceCloudResourceChart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceCloudResourceChart:
        """Test DeviceCloudResourceChart
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        if include_optional:
            return DeviceCloudResourceChart(
                key=ChartKey(
                    name='test_name',
                    version='1.0'
                ),
                latest_config=[
                    DeviceCloudResourceChartLatestConfigInner(
                        label='test_label',
                        value='test_value',
                        json_type='string',
                        required=True,
                        redacted=True
                    )
                ]
            )
        else:
            return DeviceCloudResourceChart(
                key=ChartKey(
                    name='test_name'
                )
            )

    def testDeviceCloudResourceChart(self):
        """Test DeviceCloudResourceChart"""
        inst_req_only = self.make_instance(include_optional=False)
        self.assertEqual(inst_req_only.key.name, 'test_name')
        self.assertIsNone(inst_req_only.key.version)
        self.assertIsNone(inst_req_only.latest_config)

        inst_req_and_optional = self.make_instance(include_optional=True)
        self.assertEqual(inst_req_and_optional.key.name, 'test_name')
        self.assertEqual(inst_req_and_optional.key.version, '1.0')
        self.assertIsNotNone(inst_req_and_optional.latest_config)
        self.assertEqual(inst_req_and_optional.latest_config[0].label, 'test_label')
        self.assertEqual(inst_req_and_optional.latest_config[0].value, 'test_value')
        self.assertEqual(inst_req_and_optional.latest_config[0].json_type, 'string')
        self.assertTrue(inst_req_and_optional.latest_config[0].required)
        self.assertTrue(inst_req_and_optional.latest_config[0].redacted)

if __name__ == '__main__':
    unittest.main()
