# coding: utf-8

"""
    NBI Service Orchestration API

    Provides a robust interface for orchestrating service chains across cloud and edge computing environments, facilitating deployment, management, and updates of service chains to ensure dynamic, efficient operations across diverse infrastructure setups.

    The version of the OpenAPI document: 1.0.0
    Contact: support@nearbycomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OktoStatus(str, Enum):
    """
    OktoStatus
    """

    """
    allowed enum values
    """
    OKTOSTATUS_IN_SYNC = 'OKTOSTATUS_IN_SYNC'
    OKTOSTATUS_PROGRESSING = 'OKTOSTATUS_PROGRESSING'
    OKTOSTATUS_DELETING = 'OKTOSTATUS_DELETING'
    OKTOSTATUS_ERROR = 'OKTOSTATUS_ERROR'
    OKTOSTATUS_UNKNOWN = 'OKTOSTATUS_UNKNOWN'
    OKTOSTATUS_PENDING = 'OKTOSTATUS_PENDING'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OktoStatus from a JSON string"""
        return cls(json.loads(json_str))


