# coding: utf-8

"""
    NBI Service Orchestration API

    Provides a robust interface for orchestrating service chains across cloud and edge computing environments, facilitating deployment, management, and updates of service chains to ensure dynamic, efficient operations across diverse infrastructure setups.

    The version of the OpenAPI document: 1.0.0
    Contact: support@nearbycomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inno_nbi_api.models.device import Device

class TestDevice(unittest.TestCase):
    """Device unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Device:
        """Test Device
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Device`
        """
        model = Device()
        if include_optional:
            return Device(
                id = '',
                tags = [
                    inno_nbi_api.models.device_tags_inner.Device_tags_inner(
                        key = '', 
                        value = '', )
                    ],
                display_name = '',
                position = inno_nbi_api.models.device_position.Device_position(
                    lat = 1.337, 
                    lng = 1.337, ),
                specs = '',
                status = '',
                progress = inno_nbi_api.models.device_progress.Device_progress(
                    step = 56, 
                    goal = 56, ),
                site = '',
                cloud_resource_chart = inno_nbi_api.models.device_cloud_resource_chart.Device_cloudResourceChart(
                    key = inno_nbi_api.models.chart_key.ChartKey(
                        name = '', 
                        version = '', ), 
                    latest_config = [
                        inno_nbi_api.models.device_cloud_resource_chart_latest_config_inner.Device_cloudResourceChart_latestConfig_inner(
                            label = '', 
                            value = '', 
                            json_type = '', 
                            required = True, 
                            redacted = True, )
                        ], ),
                org = ''
            )
        else:
            return Device(
        )
        """

    def testDevice(self):
        """Test Device"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
