# coding: utf-8

"""
    NBI Service Orchestration API

    Provides a robust interface for orchestrating service chains across cloud and edge computing environments, facilitating deployment, management, and updates of service chains to ensure dynamic, efficient operations across diverse infrastructure setups.

    The version of the OpenAPI document: 1.0.0
    Contact: support@nearbycomputing.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from inno_nbi_api.models.okto_status import OktoStatus

class TestOktoStatus(unittest.TestCase):
    """OktoStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOktoStatus(self):
        """Test OktoStatus"""
        # inst = OktoStatus()

if __name__ == '__main__':
    unittest.main()
